config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  constraints AuthenticatedUser.new do
    mount Sidekiq::Web, at: '/sidekiq'
    mount Blazer::Engine, at: 'blazer'
  end

  get 'reports/call_volumes'
  get 'reports/tp_calls'
  get 'reports/twilio_calls'
  get 'reports/twilio_numbers/new' => 'reports#twilio_number_new'
  post 'reports/twilio_numbers' => 'reports#twilio_number_create'
  get 'reports/where_did_you_hear'
  get 'reports/where_did_you_hear_summary'
  get 'reports/satisfaction_summary'
  get 'reports/satisfaction'
  get 'reports/costs'
  get 'reports/cost_breakdowns'
  get 'reports/cost_breakdowns_raw'

  root 'reports#call_volumes'

  resources :searches, only: :index

  resources :costs
  resources :cost_items
  resources :appointment_summaries
  resources :cita_appointment_uploads, only: %i[new create]
end

app/models/appointment_summary.rb
class AppointmentSummary < ApplicationRecord
  belongs_to :year_month

  validates :source, inclusion: { in: %w[automatic manual] }, presence: true
  validates :delivery_partner,
            inclusion: { in: Partners.delivery_partners + [Partners::WEB_VISITS] },
            uniqueness: { scope: :year_month_id }
  validates :year_month, presence: true
  validates :completions,
            numericality: true,
            inclusion: { in: ->(as) { 0..as.transactions.to_i } }
  validates :transactions, numericality: { greater_than_or_equal_to: 0 }
  validates :bookings, numericality: { greater_than_or_equal_to: 0 }

  scope :order_by_month, -> { includes(:year_month).references(:year_month).order('year_months.value') }
  scope :web, -> { where(delivery_partner: Partners::WEB_VISITS) }
  scope :non_web, -> { where.not(delivery_partner: Partners::WEB_VISITS) }

  def manual?
    source == 'manual'
  end

  def descripton
    "#{delivery_partner} #{year_month.short_format}"
  end
end

app/controllers/appointment_summaries_controller.rb
class AppointmentSummariesController < ApplicationController
  before_action :require_edit_permission!, except: %i[index show]

  def index
    @appointment_summaries = AppointmentSummaries.new(params[:appointment_summaries])
  end

  def show
    year_month = YearMonth.find_by!(value: params[:id])
    @appointment_summaries = AppointmentSummaries.new(year_month_id: year_month.id)
  end

  def new
    @appointment_summary = AppointmentSummary.new(
      delivery_partner: params[:delivery_partner],
      year_month_id: YearMonth.current.id
    )
  end

  def create
    @appointment_summary = AppointmentSummary.new(appointment_summary_params)

    if @appointment_summary.save
      redirect_to filtered_appointment_summaries(@appointment_summary)
    else
      render :new
    end
  end

  def edit
    @appointment_summary = AppointmentSummary.find(params[:id])
  end

  def update
    @appointment_summary = AppointmentSummary.find(params[:id])

    if @appointment_summary.update(appointment_summary_params)
      redirect_to filtered_appointment_summaries(@appointment_summary)
    else
      render :edit
    end
  end

  def destroy
    appointment_summary = AppointmentSummary.find(params[:id])
    flash[:notice] =
      if appointment_summary.manual?
        appointment_summary.delete
        "Deleted appointment summary for #{appointment_summary.descripton}"
      else
        "Unable to delete automatically generated appointment summary for #{appointment_summary.descripton}"
      end

    redirect_to filtered_appointment_summaries(appointment_summary)
  end

  private

  def appointment_summary_params
    params.require(:appointment_summary).permit(
      :delivery_partner,
      :year_month_id,
      :transactions,
      :bookings,
      :completions
    ).merge(source: 'manual')
  end

  def filtered_appointment_summaries(appointment_summary)
    appointment_summaries_path(appointment_summaries: { delivery_partner: appointment_summary.delivery_partner })
  end
end

app/views/appointment_summaries/_form.html.erb
<div class="form-group <%= 'form-group--error' if f.object.errors[:delivery_partner].any? %>">
  <%= f.label :delivery_partner %>
  <%= render 'shared/error', error_messages: f.object.errors[:delivery_partner] %>
  <%= f.select :delivery_partner, Partners.delivery_partners, { include_blank: true }, class: 'input-md-3 form-control t-delivery-partner text-uppercase' %>
</div>

<div class="form-group <%= 'form-group--error' if f.object.errors[:year_month_id].any? %>">
  <%= f.label :year_month_id, 'Month' %>
  <%= render 'shared/error', error_messages: f.object.errors[:year_month_id] %>
  <%= f.select :year_month_id, YearMonth.pluck(:short_format, :id), {}, class: 'input-md-3 form-control t-year-month' %>
</div>

<div class="form-group <%= 'form-group--error' if f.object.errors[:transactions].any? %>">
  <%= f.label :transactions %>
  <%= render 'shared/error', error_messages: f.object.errors[:transactions] %>
  <%= f.text_field :transactions, class: 'input-md-3 form-control t-transactions' %>
</div>

<div class="form-group <%= 'form-group--error' if f.object.errors[:bookings].any? %>">
  <%= f.label :bookings %>
  <%= render 'shared/error', error_messages: f.object.errors[:bookings] %>
  <%= f.text_field :bookings, class: 'input-md-3 form-control t-bookings' %>
</div>

<div class="form-group <%= 'form-group--error' if f.object.errors[:completions].any? %>">
  <%= f.label :completions %>
  <%= render 'shared/error', error_messages: f.object.errors[:completions] %>
  <%= f.text_field :completions, class: 'input-md-3 form-control t-completions' %>
</div>

app/views/appointment_summaries/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Edit appointment summary</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_for @appointment_summary do |f| %>
      <%= render 'form', f: f %>

      <div class="form-group">
        <%= link_to 'Cancel', appointment_summaries_path, class: 'btn btn-default' %>
        <%= f.submit 'Update', class: 'btn btn-success t-update-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/appointment_summaries/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Appointment summaries</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_for @appointment_summaries, url: appointment_summaries_path, method: 'get' do |f| %>
      <div class="form-group">
        <%= f.label :delivery_partner %>
        <%= f.select :delivery_partner, @appointment_summaries.filter_options, {}, class: 'input-md-3 form-control t-delivery_partner inline-block text-uppercase' %>
        <%= f.submit 'Filter', class: 'btn btn-success t-filter-submit' %>
        <%= link_to 'Create manual entry', new_appointment_summary_path(delivery_partner: @appointment_summaries.delivery_partner), class: 'btn btn-default' %>
        <%= link_to 'Upload CITA file', new_cita_appointment_upload_path, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @appointment_summaries.results.empty? %>
      <p class="no-content t-notice">No appointment summaries available with those filter options.</p>
    <% else %>
      <table class="table">
        <thead>
          <th>Month</th>
          <th>Bookings</th>
          <th>Completions</th>
          <th>Transactions</th>
          <th></th>
        </thead>
        <tbody>
          <% @appointment_summaries.results.each do |summary| %>
            <tr>
              <td><%= summary.year_month.short_format %></td>
              <td><%= summary.bookings %></td>
              <td><%= summary.completions %></td>
              <td><%= summary.transactions %></td>
              <td>
                <% if @appointment_summaries.merged? %>
                  <%= link_to 'By delivery partner', appointment_summary_path(summary.year_month.value), class: 'btn btn-default' %>
                <% else %>
                  <%= link_to 'Edit', edit_appointment_summary_path(summary), class: 'btn btn-default inline' %>
                  <%= button_to 'Delete', summary, method: :delete, class: 'btn btn-danger', form: { class: 'inline' } if summary.manual? %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/appointment_summaries/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>New appointment summary</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_for @appointment_summary do |f| %>
      <%= render 'form', f: f %>

      <div class="form-group">
        <%= link_to 'Cancel', appointment_summaries_path, class: 'btn btn-default' %>
        <%= f.submit 'Create', class: 'btn btn-success t-create-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/appointment_summaries/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Appointment summaries - <%= @appointment_summaries.month %></h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @appointment_summaries.results.empty? %>
      <p class="no-content t-notice">No appointment summaries available with those filter options.</p>
    <% else %>
      <table class="table">
        <thead>
          <th>Delivery partner</th>
          <th>Bookings</th>
          <th>Completions</th>
          <th>Transactions</th>
          <th></th>
        </thead>
        <tbody>
          <% @appointment_summaries.results.each do |summary| %>
            <tr>
              <td><%= summary.delivery_partner.upcase %></td>
              <td><%= summary.bookings %></td>
              <td><%= summary.completions %></td>
              <td><%= summary.transactions %></td>
              <td>
                <%= link_to "Edit", edit_appointment_summary_path(summary), class: 'btn btn-default inline' %>
                <%= button_to "Delete", summary, method: :delete, class: 'btn btn-danger', form: { class: 'inline' } if summary.manual? %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>