config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  constraints AuthenticatedUser.new do
    mount Sidekiq::Web, at: '/sidekiq'
    mount Blazer::Engine, at: 'blazer'
  end

  get 'reports/call_volumes'
  get 'reports/tp_calls'
  get 'reports/twilio_calls'
  get 'reports/twilio_numbers/new' => 'reports#twilio_number_new'
  post 'reports/twilio_numbers' => 'reports#twilio_number_create'
  get 'reports/where_did_you_hear'
  get 'reports/where_did_you_hear_summary'
  get 'reports/satisfaction_summary'
  get 'reports/satisfaction'
  get 'reports/costs'
  get 'reports/cost_breakdowns'
  get 'reports/cost_breakdowns_raw'

  root 'reports#call_volumes'

  resources :searches, only: :index

  resources :costs
  resources :cost_items
  resources :appointment_summaries
  resources :cita_appointment_uploads, only: %i[new create]
end

app/models/cost_item.rb
class CostItem < ApplicationRecord
  has_many :costs

  def self.allowed_delivery_partners
    Partners.delivery_partners + CostPerTransaction::DELIVERY_PARTNER_BREAKDOWN_METHODS
  end

  validates :name, :cost_group, presence: true
  validates :delivery_partner, inclusion: { in: allowed_delivery_partners, allow_blank: true }

  scope :current, -> { reporting_includes.where(current: true) }
  scope :during_months, ->(year_months) { reporting_includes.where(costs: { year_month_id: year_months }) }
  scope :reporting_includes, -> { includes(costs: :year_month) }
end

app/controllers/cost_items_controller.rb
class CostItemsController < ApplicationController
  before_action :require_edit_permission!, except: :index

  def index
    @highlight = CostItem.find_by(id: params[:highlight_id])
    @cost_items = CostItem.current
                          .order(:cost_group, :name)
                          .group_by(&:cost_group)
  end

  def new
    @cost_item = CostItem.new
  end

  def create
    @cost_item = CostItem.new(cost_item_params)

    if @cost_item.save
      redirect_to cost_items_path(anchor: "cost-item-#{@cost_item.id}")
    else
      render :new
    end
  end

  def edit
    @cost_item = CostItem.find(params[:id])
  end

  def update
    @cost_item = CostItem.find(params[:id])

    if @cost_item.update(cost_item_params)
      redirect_to cost_items_path(anchor: "cost-item-#{@cost_item.id}")
    else
      render :edit
    end
  end

  def destroy
    @cost_item = CostItem.find(params[:id])
    @cost_item.update(current: false)

    redirect_to cost_items_path
  end

  private

  def cost_item_params
    params.require(:cost_item).permit(
      :name,
      :cost_group,
      :web_cost,
      :delivery_partner
    )
  end
end

app/views/cost_items/_form.html.erb
<div class="form-group <%= 'form-group--error' if f.object.errors[:name].any? %>">
  <%= f.label :name %>
  <%= render 'shared/error', error_messages: f.object.errors[:name] %>
  <%= f.text_field :name, class: 'input-md-3 form-control' %>
</div>

<div class="form-group <%= 'form-group--error' if f.object.errors[:cost_group].any? %>">
  <%= f.label :cost_group %>
  <%= render 'shared/error', error_messages: f.object.errors[:cost_group] %>
  <%= f.select :cost_group, CostItem.distinct.pluck(:cost_group).sort, {}, class: 'input-md-3 form-control' %>
</div>

<div class="form-group <%= 'form-group--error' if f.object.errors[:web_cost].any? %>">
  <%= f.label :web_cost %>
  <%= render 'shared/error', error_messages: f.object.errors[:web_cost] %>
  <br />
  <label>
    <%= f.radio_button :web_cost, true, class: '' %>
    Yes
  </label>
  <label>
    <%= f.radio_button :web_cost, false, class: '' %>
    No
  </label>
</div>

<div class="form-group <%= 'form-group--error' if f.object.errors[:delivery_partner].any? %>">
  <%= f.label :delivery_partner %>
  <%= render 'shared/error', error_messages: f.object.errors[:delivery_partner] %>
  <%= f.select :delivery_partner, CostItem.allowed_delivery_partners.map { |p| [p.humanize, p] }, { include_blank: true }, class: 'input-md-3 form-control' %>
</div>

app/views/cost_items/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Cost item - <%= @cost_item.name %></h1>
  </div>
</div>

<%= form_for @cost_item do |f| %>
  <%= render 'form', f: f %>

  <div class="form-group">
    <%= link_to 'Cancel', cost_items_path, class: 'btn btn-default' %>
    <%= f.submit 'Update', class: 'btn btn-success t-update-button' %>
  </div>
<% end %>

app/views/cost_items/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Cost items</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Add new', new_cost_item_path, class: 'btn btn-success' %>

    <table class="table table-hover">
      <thead>
      <tr>
        <th class="col-md-2">Name</th>
        <th class="col-md-2">Web cost</th>
        <th class="col-md-2">Delivery partner</th>
        <th class="col-md-2"></th>
      </tr>
      <% @cost_items.each do |cost_group, costs_item| %>

        <thead>
          <tr class="l-costs__header">
            <td colspan="4"><%= cost_group %></td>
          </tr>
        </thead>
        <tbody>
          <% costs_item.each do |cost_item| %>
            <tr id="cost-item-<%= cost_item.id %>">
              <td><%= cost_item.name %></td>
              <td><%= cost_item.web_cost ? 'Yes' : 'No' %></td>
              <td><%= cost_item.delivery_partner.humanize %></td>
              <td>
                <%= link_to 'Edit', edit_cost_item_path(cost_item), class: 'btn btn-default' %>
                <%= button_to 'Delete', cost_item_path(cost_item), method: 'delete', class: 'btn btn-danger', form_class: 'inline', data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </table>
    <%= link_to 'Add new', new_cost_item_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/cost_items/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Cost item - <%= @cost_item.name %></h1>
  </div>
</div>

<%= form_for @cost_item do |f| %>
  <%= render 'form', f: f %>

  <div class="form-group">
    <%= link_to 'Cancel', cost_items_path, class: 'btn btn-default' %>
    <%= f.submit 'Create', class: 'btn btn-success t-update-button' %>
  </div>
<% end %>