config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  constraints AuthenticatedUser.new do
    mount Sidekiq::Web, at: '/sidekiq'
    mount Blazer::Engine, at: 'blazer'
  end

  get 'reports/call_volumes'
  get 'reports/tp_calls'
  get 'reports/twilio_calls'
  get 'reports/twilio_numbers/new' => 'reports#twilio_number_new'
  post 'reports/twilio_numbers' => 'reports#twilio_number_create'
  get 'reports/where_did_you_hear'
  get 'reports/where_did_you_hear_summary'
  get 'reports/satisfaction_summary'
  get 'reports/satisfaction'
  get 'reports/costs'
  get 'reports/cost_breakdowns'
  get 'reports/cost_breakdowns_raw'

  root 'reports#call_volumes'

  resources :searches, only: :index

  resources :costs
  resources :cost_items
  resources :appointment_summaries
  resources :cita_appointment_uploads, only: %i[new create]
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def call_volumes
    @call_volumes = CallVolumes.new(**date_params(:call_volumes))

    respond_to do |format|
      format.html
      format.csv do
        render csv: DailyCallVolumeCsv.new(@call_volumes.results), filename: 'daily_call_volume.csv'
      end
    end
  end

  def costs
    @costs = costs_report
  end

  def cost_breakdowns
    render csv: CostBreakdownCsv.build(costs_report), filename: 'cost_breakdown.csv'
  end

  def cost_breakdowns_raw
    render csv: CostBreakdownRawCsv.new(costs_report.raw), filename: 'cost_breakdown_raw.csv'
  end

  def tp_calls
    @call_volumes = CallVolumes.new(**date_params(:call_volumes))

    respond_to do |format|
      format.csv do
        render csv: TpCallsCsv.new(@call_volumes.tp_calls), filename: 'tp_calls.csv'
      end
    end
  end

  def twilio_calls
    @call_volumes = CallVolumes.new(**date_params(:call_volumes))

    respond_to do |format|
      format.csv do
        render csv: TwilioCallsCsv.new(@call_volumes.twilio_calls), filename: 'twilio_calls.csv'
      end
    end
  end

  def satisfaction_summary
    @satisfactions = Satisfactions.new(**satisfaction_params)
    @satisfaction_summary = SatisfactionSummary.new(@satisfactions.results, @satisfactions.year_month)

    respond_to do |format|
      format.html
      format.csv do
        render csv: SatisfactionSummaryCsv.new(@satisfaction_summary.rows), filename: 'satisfaction_data.csv'
      end
    end
  end

  def satisfaction
    @satisfactions = Satisfactions.new(**satisfaction_params)

    respond_to do |format|
      format.csv { render csv: SatisfactionCsv.new(@satisfactions.results), filename: 'satisfaction_data_raw.csv' }
    end
  end

  def where_did_you_hear
    @where_did_you_hears = WhereDidYouHears.new(**where_did_you_hear_params)

    respond_to do |format|
      format.html
      format.csv do
        render csv: WhereDidYouHearCsv.new(@where_did_you_hears.results), filename: 'where_did_you_hear.csv'
      end
    end
  end

  def where_did_you_hear_summary
    @where_did_you_hears = WhereDidYouHears.new(**where_did_you_hear_params)
    @report = WhereDidYouHearSummary.new(@where_did_you_hears.results)
  end

  def twilio_number_new
    @twilio_numbers_report = TwilioNumbersReport.new

    render 'twilio_numbers'
  end

  def twilio_number_create
    @twilio_numbers_report = TwilioNumbersReport.new(twilio_numbers_report_params)

    if @twilio_numbers_report.valid?
      GenerateTwilioNumbersReport.perform_later(@twilio_numbers_report.emails)
      flash[:success] = "Successfully requested Twilio numbers report for: #{@twilio_numbers_report.email}"
      redirect_to reports_twilio_numbers_new_path
    else
      render 'twilio_numbers'
    end
  end

  private

  def costs_report
    CostsReport.new(
      start_month_id: params.dig(:costs_report, :start_month_id),
      end_month_id: params.dig(:costs_report, :end_month_id)
    )
  end

  def where_did_you_hear_params
    date_params(:where_did_you_hears).merge(page: params[:page])
  end

  def satisfaction_params
    { year_month_id: params.dig(:satisfactions, :year_month_id) }
  end

  def date_params(namespace)
    {
      start_date: params.dig(namespace, :start_date),
      end_date: params.dig(namespace, :end_date)
    }
  end

  def twilio_numbers_report_params
    params.require(:twilio_numbers_report).permit(:email)
  end
end

app/views/reports/_cost_per.html.erb
<div class="l-costs__component t-total-cost"><%= number_to_currency(object.total_cost, unit: '£') %></div>
<div class="l-costs__component"><%= object.transactions %></div>
<div class="l-costs__value <%= local_assigns[:class_name] %>"><%= number_to_currency(object.value, unit: '£') %></div>

app/views/reports/_error.html.erb
<% if error_messages.any? %>
  <%= simple_format error_messages.join("\n"), { class: 'form-group__error-message' }, wrapper_tag: 'span' %>
<% end %>

app/views/reports/_where_did_you_hear_filters.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <%= form_for @where_did_you_hears, url: reports_where_did_you_hear_path, method: :get, html: { class: 'inline form-inline' } do |f| %>
        <div class="form-group">
          <%= f.label :start_date, 'From', class: 'inline' %>
          <%= f.text_field :start_date, type: :date, class: 'form-control t-start', placeholder: 'dd/mm/yyyy' %>
        </div>
        <div class="form-group">
          <%= f.label :end_date, 'To', class: 'inline' %>
          <%= f.text_field :end_date, type: :date, class: 'form-control t-end', placeholder: 'dd/mm/yyyy' %>
        </div>
        <%= f.submit 'Search', class: 'btn btn-default t-search' %>
      <% end %>

      <%= form_for @where_did_you_hears, url: reports_where_did_you_hear_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :start_date %>
        <%= f.hidden_field :end_date %>
        <%= f.submit 'Export CSV', class: 'btn btn-default t-export' %>
      <% end %>

      <%= form_for @where_did_you_hears, url: reports_where_did_you_hear_summary_path, method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :start_date %>
        <%= f.hidden_field :end_date %>
        <%= f.submit 'Summary', class: 'btn btn-default t-summary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/call_volumes.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Call volumes</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <%= form_for @call_volumes, url: reports_call_volumes_path, method: :get, html: { class: 'inline form-inline' } do |f| %>
        <div class="form-group">
          <%= f.label :start_date, 'From', class: 'inline' %>
          <%= f.text_field :start_date, type: :date, class: 'form-control t-start-date', placeholder: 'dd/mm/yyyy' %>
        </div>
        <div class="form-group">
          <%= f.label :end_date, 'To', class: 'inline' %>
          <%= f.text_field :end_date, type: :date, class: 'form-control t-end-date', placeholder: 'dd/mm/yyyy' %>
        </div>
        <%= f.submit 'Search', class: 'btn btn-default t-search' %>
      <% end %>

      <%= form_for @call_volumes, url: reports_call_volumes_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :start_date %>
        <%= f.hidden_field :end_date %>
        <%= f.submit 'Export CSV', class: 'btn btn-default t-export-csv' %>
      <% end %>

      <%= form_for @call_volumes, url: reports_twilio_calls_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :start_date %>
        <%= f.hidden_field :end_date %>
        <%= f.submit 'Export twilio calls CSV', class: 'btn btn-default t-export-twilio-calls-csv' %>
      <% end %>

      <%= form_for @call_volumes, url: reports_tp_calls_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :start_date %>
        <%= f.hidden_field :end_date %>
        <%= f.submit 'Export TP calls CSV', class: 'btn btn-default t-export-tp-calls-csv' %>
      <% end %>
    </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Day</th>
          <th>Contact centre</th>
          <th colspan="5">Twilio</th>
        </tr>
        <tr>
          <th></th>
          <th></th>
          <th>Total</th>
          <th>Total</th>
          <th>CAS</th>
          <th>CITA</th>
          <th>NICAB</th>
          <th>Unknown</th>
        </tr>
      </thead>
      <tbody>
        <%- @call_volumes.results.each do |daily_call_volume| %>
          <tr class="t-call-day">
            <td class="t-call-date"><%= daily_call_volume.date.to_s(:govuk_date) %></td>
            <td><%= daily_call_volume.date.strftime('%a') %></td>
            <td class="t-contact-centre-calls"><%= daily_call_volume.contact_centre %></td>
            <td class="t-twilio-calls"><%= daily_call_volume.twilio %></td>
            <td><%= daily_call_volume.twilio_cas %></td>
            <td><%= daily_call_volume.twilio_cita %></td>
            <td><%= daily_call_volume.twilio_nicab %></td>
            <td><%= daily_call_volume.twilio_unknown %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td>Total</td>
          <td>&nbsp;</td>
          <td class="t-total-contact-centre-calls"><%= number_with_delimiter @call_volumes.total_calls.contact_centre %></td>
          <td class="t-total-twilio-calls"><%= number_with_delimiter @call_volumes.total_calls.twilio %></td>
          <td><%= number_with_delimiter @call_volumes.total_calls.twilio_cas %></td>
          <td><%= number_with_delimiter @call_volumes.total_calls.twilio_cita %></td>
          <td><%= number_with_delimiter @call_volumes.total_calls.twilio_nicab %></td>
          <td><%= number_with_delimiter @call_volumes.total_calls.twilio_unknown %></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/reports/costs.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Costs by month</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <%= form_for @costs, url: reports_costs_path, method: :get, html: { class: 'inline form-inline' } do |f| %>
        <div class="form-group">
          <%= f.label :start_month_id, 'From', class: 'inline' %>
          <%= f.select :start_month_id, YearMonth.pluck(:short_format, :id), {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :end_month_id, 'To', class: 'inline' %>
          <%= f.select :end_month_id, YearMonth.pluck(:short_format, :id), {}, class: 'form-control' %>
        </div>
        <%= f.submit 'Search', class: 'btn btn-default t-search' %>
      <% end %>
      <%= form_for @costs, url: reports_cost_breakdowns_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :start_month_id %>
        <%= f.hidden_field :end_month_id %>
        <%= f.submit 'Export Breakdown CSV', class: 'btn btn-default t-export-csv' %>
      <% end %>
      <%= form_for @costs, url: reports_cost_breakdowns_raw_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :start_month_id %>
        <%= f.hidden_field :end_month_id %>
        <%= f.submit 'Export Raw CSV', class: 'btn btn-default t-export-csv' %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @costs.by_month.empty? %>
      <h3>Please check your month range and try again.</h3>
    <% else %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="col-md-1">Month</th>
            <th class="col-md-2"></th>
            <th class="col-md-1 text-center">Overall</th>
            <th class="col-md-1 text-center">Web</th>
            <th class="col-md-1 text-center">CAS</th>
            <th class="col-md-1 text-center">CITA</th>
            <th class="col-md-1 text-center">NICAB</th>
            <th class="col-md-1 text-center">TPAS</th>
          </tr>
        </thead>
        <tbody>
          <% @costs.by_month.each do |costs| %>
            <tr class="t-months">
              <td class="t-month-name"><%= costs.year_month.short_format %></td>
              <td>
                <div class="l-costs__component">Total cost:</div>
                <div class="l-costs__component">Transactions:</div>
                <div class="l-costs__value">Cost / Transaction</div>
              </td>
              <td><%= render 'cost_per', object: costs.overall, class_name: 't-overall' %></td>
              <td class="t-web"><%= render 'cost_per', object: costs.web %></td>
              <td><%= render 'cost_per', object: costs.cas, class_name: 't-cas' %></td>
              <td><%= render 'cost_per', object: costs.cita, class_name: 't-cita' %></td>
              <td><%= render 'cost_per', object: costs.nicab, class_name: 't-nicab' %></td>
              <td><%= render 'cost_per', object: costs.tpas, class_name: 't-tpas' %></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tfoot>
      </table>
    <% end %>

    <%= link_to 'Add costs', costs_path, class: 'btn btn-success' if current_user.has_permission?('analyst') %>
  </div>
</div>

app/views/reports/satisfaction_summary.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Satisfaction</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <%= form_for @satisfactions, url: reports_satisfaction_summary_path, method: :get, html: { class: 'inline form-inline' } do |f| %>
        <div class="form-group">
          <%= f.label :year_month_id, 'Month', class: 'inline' %>
          <%= f.select :year_month_id, @satisfactions.months.pluck(:short_format, :id), {}, class: 'form-control t-month' %>
        </div>
        <%= f.submit 'Search', class: 'btn btn-default t-search' %>
      <% end %>

      <%= form_for @satisfactions, url: reports_satisfaction_summary_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :year_month_id %>
        <%= f.submit 'Export CSV', class: 'btn btn-default t-export-csv' %>
      <% end %>

      <%= form_for @satisfactions, url: reports_satisfaction_path(format: :csv), method: :get, html: { class: 'inline form-inline' } do |f| %>
        <%= f.hidden_field :year_month_id %>
        <%= f.submit 'Export raw CSV', class: 'btn btn-default t-export-raw-csv' %>
      <% end %>
    </div>
  </div>
</div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-bordered">
      <thead>
        <tr class="table-header">
          <th scope="col"></th>
          <th>CAS</th>
          <th>CAS Telephone</th>
          <th>CITA</th>
          <th>CITA Telephone</th>
          <th>NICAB</th>
          <th>NICAB Telephone</th>
          <th>TPAS</th>
          <th>TP</th>
          <th>Total</th>
          <th>Weighted average</th>
        </tr>
      </thead>
      <tbody>
        <%- @satisfaction_summary.rows.each do |row| %>
          <tr class="t-row">
            <td><%= row.name %></td>
            <td class="text-right"><%= row.cas %></td>
            <td class="text-right"><%= row.cas_telephone %></td>
            <td class="text-right"><%= row.cita %></td>
            <td class="text-right"><%= row.cita_telephone %></td>
            <td class="text-right"><%= row.nicab %></td>
            <td class="text-right"><%= row.nicab_telephone %></td>
            <td class="text-right"><%= row.tpas %></td>
            <td class="text-right"><%= row.tp %></td>
            <td class="text-right"><%= row.total %></td>
            <td class="text-right"><%= row.weighted_average %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/reports/twilio_numbers.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Twilio numbers report request</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <%= form_for @twilio_numbers_report, url: reports_twilio_numbers_path do |f| %>
        <div class="form-group <%= 'form-group--error' if f.object.errors[:email].any? %>">
          <%= f.label :email %>
          <%= render 'error', error_messages: f.object.errors[:email] %>
          <%= f.text_field :email, class: 'input-md-6 form-control' %>
        </div>

        * Comma separated list of users to be emailed the generated report
        <div class="form-group">
          <%= f.submit 'Request report', class: 'btn btn-default t-search' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/where_did_you_hear.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Where did you hear about us?</h1>
  </div>
</div>
<%= render 'where_did_you_hear_filters' %>
<div class="row">
  <div class="col-md-12">
    <%= paginate @where_did_you_hears.paginated_results, theme: 'twitter-bootstrap-3' %>

    <table class="table table-striped table-bordered">
      <thead>
        <tr class="table-header">
          <th scope="col">Given at</th>
          <th scope="col">Where they heard (RAW)</th>
          <th scope="col">Where they heard</th>
          <th scope="col">Partner</th>
          <th scope="col">Location</th>
        </tr>
      </thead>
      <tbody>
        <%- @where_did_you_hears.paginated_results.each do |where_did_you_hear| %>
          <tr class="t-row">
            <td><%= where_did_you_hear.given_at.to_s(:govuk_date) %></td>
            <td><%= where_did_you_hear.heard_from_raw %></td>
            <td><%= where_did_you_hear.heard_from %></td>
            <td><%= where_did_you_hear.delivery_partner %></td>
            <td><%= where_did_you_hear.location %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @where_did_you_hears.paginated_results, theme: 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/reports/where_did_you_hear_summary.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Where did you hear about us?</h1>
  </div>
</div>
<%= render 'where_did_you_hear_filters' %>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-bordered">
      <thead>
        <tr class="table-header">
          <th scope="col">Where they heard</th>
          <th scope="col">Responses</th>
          <th scope="col">Percentage</th>
        </tr>
      </thead>
      <tbody>
        <%- @report.rows.each do |row| %>
          <tr class="t-row">
            <td><%= row.heard_from %></td>
            <td><%= row.count %></td>
            <td><%= number_to_percentage(row.percentage, precision: 2) %></td>
          </tr>
        <% end %>
        <tr class="t-footer">
          <td>Total:</td>
          <td><%= @report.total %></td>
          <td>100</td>
        </td>
      </tbody>
    </table>
  </div>
</div>