config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  constraints AuthenticatedUser.new do
    mount Sidekiq::Web, at: '/sidekiq'
    mount Blazer::Engine, at: 'blazer'
  end

  get 'reports/call_volumes'
  get 'reports/tp_calls'
  get 'reports/twilio_calls'
  get 'reports/twilio_numbers/new' => 'reports#twilio_number_new'
  post 'reports/twilio_numbers' => 'reports#twilio_number_create'
  get 'reports/where_did_you_hear'
  get 'reports/where_did_you_hear_summary'
  get 'reports/satisfaction_summary'
  get 'reports/satisfaction'
  get 'reports/costs'
  get 'reports/cost_breakdowns'
  get 'reports/cost_breakdowns_raw'

  root 'reports#call_volumes'

  resources :searches, only: :index

  resources :costs
  resources :cost_items
  resources :appointment_summaries
  resources :cita_appointment_uploads, only: %i[new create]
end

app/views/layouts/application.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
<% end %>

<%= content_for :app_title do %>
  Reporting
<% end %>

<%= content_for :navbar_items do %>
  <li>
    <%= link_to 'Blazer', '/blazer' if Rails.env.production? %>
  </li>
  <li>
    <%= link_to 'Appointments', appointment_summaries_path %>
  </li>
  <li>
    <%= link_to 'Call volumes', reports_call_volumes_path %>
  </li>
  <li>
    <%= link_to 'Search', searches_path %>
  </li>
  <li>
    <%= link_to 'Satisfaction', reports_satisfaction_summary_path %>
  </li>
  <li>
    <%= link_to 'Twilio numbers', reports_twilio_numbers_new_path %>
  </li>
  <li>
    <%= link_to 'Where did you hear?', reports_where_did_you_hear_path %>
  </li>
<% end %>

<% content_for :body_end do %>
  <%= javascript_include_tag 'application' %>
<% end %>

<%= render template: 'layouts/govuk_admin_template' %>